# 线上配置文件
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://154.9.254.66:3306/user_center?useSSL=false'
    username: user_center
    password: Qwsx951753/
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
